OP-TEE/optee_website

security-advisories/security-advisories.md

Add all details and links to fixes etc, we will get the CVE number when we have provided all this on the public page. Once this has been put on optee.org I will Kurt from Mitre now and then we will get the CVE numbers for it.

Update text for OP-TEE security issue 0002 and 0003

---

about/README.md

Updated title
Description was missing

Updated title & description

---

faq/README.md

Signed-off-by: Victor Chong <victor.chong@linaro.org>

faq: readme: Add entry for calling op-tee from android .apk apps

---

404.html

404 Permalink updated

---

build/README.md
faq/README.md

OP-TEE broken links 

---

404.html
roadmap/roadmap.md

Updated Roadmap Page

---

roadmap/roadmap.md

Removed src of roadmap iframe

---

_posts/2017-10-23-security-session-highlights-from-sfo17.md

Changed the title of blog post to lowercase and changed front matter for featured_image
@shovanuk

Updated new OP-TEE Blog Post.

---

_assets/css/custom.scss

Moved title up 5 px to fix alignment issue

---

faq/README.md

faq.md: Updated section about TEE driver in Linux

---

faq/README.md

There is a opened P-R in optee_examples that will provide guidelines and examples: https://github.com/linaro-swg/optee_examples/pull/9.
I will notify when it is merged.

Update from TA build info available in optee_examples

---

security-advisories/security-advisories.md

@shovanuk @kylekirkby , first set of information to share publicly regarding the Meltdown and Spectre attacks. There will be updates to this page in the near future, but I think I'd like to get the current changes merged.
(I've also sneaked in the CVE number to two older issues, Mitre finally gave them to me).
// Joakim

Meltdown spectre 01

---

security-advisories/security-advisories.md

Here is the second update to Meltdown and Spectre. Changes are based on changed patch statuses, new patches etc. I've also corrected some information and clarified in some other places.

Spectre, Meltdown: Update 2

---

build/README.md
docs/hikey.md

Fixed broken links 
Page: https://www.op-tee.org/build/
Broken Link: 
MediaTek MT8173 EVB Board 
http://www.mediatek.com/en/products/mobile-communications/tablet/mt8173
Correct Link: https://www.mediatek.com/products/tablets/mt8173
Page: https://www.op-tee.org/docs/hikey/
Broken Link:
official HiKey documentation 
http://www.96boards.org/documentation/ConsumerEdition/HiKey/README.md
Correct link >> https://www.96boards.org/documentation/ConsumerEdition/HiKey/

Fixed broken linked

---

_data/settings.yml

Updated the settings.yml file

---

_data/authors.yml
_posts/2016-07-04-hkg15-303-secure-playback-using-op-tee.md
_posts/2016-07-04-hkg15-307-op-tee-paging.md
_posts/2016-07-04-hkg15-311-op-tee-beginners-porting-review.md
_posts/2016-07-04-hkg15-505-power-management-interactions-op-tee-trusted-firmware.md
_posts/2016-07-04-lcu14-103-create-run-trusted-applications-op-tee.md
_posts/2016-07-04-lcu14-107-op-tee-armv8.md
_posts/2016-07-04-lcu14-302-op-tee-porting-future-enhancements.md
_posts/2016-07-04-sfo15-200-linux-kernel-generic-tee-driver.md
_posts/2016-07-04-sfo15-205-op-tee-content-microsoft-playready-arm-trustzone.md
_posts/2016-07-04-sfo15-503-secure-storage-op-tee.md
_posts/2017-03-17-benchmark-profiling-op-tee-bud17-416-view-pathable.markdown
_posts/2017-03-17-bof-device-tree-secure-firmware-bud17-313.markdown
_posts/2017-03-17-power-management-linux-together-secure-firmware-bud17-510.markdown
_posts/2017-03-17-universal-keyring-time-come-bud17-203.md
_posts/2017-06-02-op-tee-qa.md
_posts/2017-06-02-webinar-tee-kernel-support-now-upstream-means-open-source-security.md
_posts/2017-10-23-security-session-highlights-from-sfo17.md
legal/README.md

Updates as requested :)
@shovanuk

OP-TEE Updates

---

_data/nav.yml
_data/sub-nav.yml
_posts/2017-06-02-op-tee-qa.md
build/README.md
docs/debug.md
docs/hikey.md
docs/juno.md
docs/rpi3.md
docs/ti.md
documentation/README.md
faq/README.md

This is a general update and should hopefully also take care of the bad links mentioned in #46 . Due to this I believe it is better to merge this PR first, then rebase #46 and then merge that.
// Joakim

Update optee pages

---

security-advisories/README.md

Security Advisories: Add information about Spectre v4

---

posts.json.html

Added the posts.json.html file which outputs json data of all the OP-TEE posts for aggregation on the Linaro.org resources page

Added the posts.json.html file

---

docs/README.md
docs/debug.md
docs/rpi3.md

Broken link fix / layouts changed

Broken link fix / layouts changed

---

Gemfile
Gemfile.lock

Updated theme to fix flexbox bug on chrome

Updated theme to fix flexbox bug on chrome

---

_posts/2017-06-02-op-tee-qa.md
assets/json/posts.json.html
legal/README.md

Removed extra space to see if it effects javascript from pulling data..
https://www.op-tee.org/assets/json/posts.json

Removed extra space to see if it effects javascript from pulling data..

---

security-advisories/README.md

Out of all potentially security issues reported by Riscure as an outcome
of their "mini-audit" we narrowed down seven of them as higher severity.
These are the ones that has been mentioned in this patch.
CVE numbers have been requested, but we haven't got them yet. If/when we
get those, we will submit another update patch.

Security Advisories: Add information from Riscure mini-audit

---

security-advisories/README.md

Updated the LibTomCrypt reference

Updated the LibTomCrypt reference

---

_pages/security-advisories/README.md

Add contents for CVE-2018-12437, OP-TEE-2019-0018.

Security Advisories: Add information about CVE-2018-12437

---

_data/settings.yml

Adding missing analytics code

---

_data/universal-nav.yml

Removed ODP from the universal nav

Removed ODP from the universal nav

---

_data/universal-nav.yml

Added OpenAMP to universal nav

Added OpenAMP to universal nav

---

assets/css/app/custom.scss
index.md

Fixing merge conflicts

---

_pages/security_advisories.md

This should have been done a long time ago, so please review and merge.
Add information about:
- OP-TEE-2019-0019
- OP-TEE-2019-0020
- OP-TEE-2019-0021

Security Advisories: Add OP-TEE-2019-{0019,0020,0021}

---

_config-production.yml
_config.yml
assets/js/app/main.js

Adding Google Tag Manager with the new GA4 analytics property since the previous property is reaching end-of-life

Adding Google Tag Manager + GA4 property
